services:
  devbox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ubuntu_dev
    volumes:
      - ./frontend:/home/devuser/app
    ports:
      - "5173:5173" # porta do Vite
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
  # db:
  #   image: postgres:16
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: fullstack_db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   restart: always
  #   environment:
  #     PORT: 3333
  #     HOST: 0.0.0.0
  #     DB_CONNECTION: pg
  #     PG_HOST: db
  #     PG_PORT: 5432
  #     PG_USER: user
  #     PG_PASSWORD: password
  #     PG_DB_NAME: fullstack_db
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  #   ports:
  #     - "3333:3333"
